import React, { useEffect, useState } from "react";
import {
  Box,
  Container,
  Paper,
  Typography,
  Divider,
  Button,
} from "@mui/material";
import PurchaseInvoiceForm from "../components/PurchaseInvoice/PurchaseInvoiceForm";
import PurchaseInvoicePreview from "../components/PurchaseInvoice/PurchaseInvoicePreview";
import apiClient from "../services/apiClient";

export default function PurchaseInvoicePage() {
  const [form, setForm] = useState({
    invoiceId: "", // ✅ Empty - will be generated by backend
    invoiceDate: new Date().toISOString().slice(0, 10),
    supplier: "",
    supplierAddress: "",
    supplierId: null,
    vehicleNo: "",
    deliveryLocation: "",
    paymentMode: "CASH",
    remarks: "",
    gstAmount: "0.00",
    warehouse: "",
    items: [
      {
        hsn: "",
        description: "",
        brand: "",
        size: "",
        grade: "",
        qty: "",
        unit: "",
        rate: "",
        amount: "",
        category: "",
        productId: "",
      },
    ],
    subtotal: "0.00",
    grandTotal: "0.00",
    amountInWords: "",
  });

  const [isSaving, setIsSaving] = useState(false);
  const [warehouses, setWarehouses] = useState([]);

  useEffect(() => {
    apiClient.get("/api/warehouses").then((r) => setWarehouses(r.data));
  }, []);

  const updateField = (key, value) => setForm((p) => ({ ...p, [key]: value }));

  const updateItem = (index, key, value) => {
    const items = [...form.items];
    items[index] = { ...items[index], [key]: value };

    if (key === "qty" || key === "rate") {
      const qty = parseFloat(items[index].qty || 0);
      const rate = parseFloat(items[index].rate || 0);
      items[index].amount =
        !isNaN(qty) && !isNaN(rate) ? (qty * rate).toFixed(2) : "";
    }
    setForm((p) => ({ ...p, items }));
  };

  const addItemRow = () => {
    setForm((p) => ({
      ...p,
      items: [
        ...p.items,
        {
          hsn: "",
          description: "",
          brand: "",
          size: "",
          grade: "",
          qty: "",
          unit: "",
          rate: "",
          amount: "",
          category: "",
          productId: "",
        },
      ],
    }));
  };

  const removeItemRow = (index) => {
    const items = form.items.filter((_, i) => i !== index);
    setForm((p) => ({ ...p, items }));
  };

  useEffect(() => {
    const subtotal = form.items.reduce(
      (s, it) => s + Number(it.amount || 0),
      0
    );
    const gst = parseFloat(form.gstAmount || 0);
    const grand = subtotal + gst;
    setForm((p) => ({
      ...p,
      subtotal: subtotal.toFixed(2),
      grandTotal: grand.toFixed(2),
      amountInWords: numberToWordsIndian(Math.round(grand)),
    }));
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [form.items, form.gstAmount]);

  const handlePrint = () => {
    window.print();
  };

  const handleSubmitInvoice = async () => {
    try {
      setIsSaving(true);

      const payload = {
        // ❌ Don't send invoiceId - backend will generate it
        invoiceDate: form.invoiceDate,
        warehouseId: parseInt(form.warehouse),
        supplierId: parseInt(form.supplierId),
        supplierName: form.supplier || "Walk-in Supplier",
        supplierAddress: form.supplierAddress || "",
        paymentMode: form.paymentMode,
        vehicleNo: form.vehicleNo,
        deliveryLocation: form.deliveryLocation,
        remarks: form.remarks,
        items: form.items
          .filter((item) => item.productId && item.qty && item.rate)
          .map((i) => ({
            productId: parseInt(i.productId),
            unitId: 1,
            quantity: parseFloat(i.qty),
            purchasePrice: parseFloat(i.rate),
            amount: parseFloat(i.amount),
          })),
        totalAmount: parseFloat(form.grandTotal),
      };

      console.log("📤 Sending payload:", payload);

      const response = await apiClient.post("/api/purchases", payload);

      // ✅ Update form with generated invoice number
      setForm((prev) => ({
        ...prev,
        invoiceId: response.data.invoiceNo,
      }));

      setIsSaving(false);
      alert(
        `✅ Purchase Invoice ${response.data.invoiceNo} saved successfully!`
      );
    } catch (err) {
      console.error("Error saving purchase invoice:", err);
      setIsSaving(false);
      alert(err.response?.data?.message || "Failed to save purchase invoice");
    }
  };

  const handleClearForm = () => {
    setForm({
      invoiceId: "",
      invoiceDate: new Date().toISOString().slice(0, 10),
      supplier: "",
      supplierAddress: "",
      supplierId: null,
      vehicleNo: "",
      deliveryLocation: "",
      paymentMode: "CASH",
      remarks: "",
      gstAmount: "0.00",
      warehouse: "",
      items: [
        {
          hsn: "",
          description: "",
          brand: "",
          size: "",
          grade: "",
          qty: "",
          unit: "",
          rate: "",
          amount: "",
          category: "",
          productId: "",
        },
      ],
      subtotal: "0.00",
      grandTotal: "0.00",
      amountInWords: "",
    });
  };

  return (
    <Container maxWidth="lg" sx={{ mt: 3 }}>
      <style>{`
        @media print {
          body * { visibility: hidden; }
          .printable-area, .printable-area * { visibility: visible; }
          .printable-area { position: absolute; left: 0; top: 0; width: 100%; }
        }
        .purchase-preview-root { margin-top: 16px; }
      `}</style>

      <Paper sx={{ p: 3 }}>
        <Typography variant="h5" gutterBottom>
          Purchase Invoice (Entry)
        </Typography>
        <Typography variant="body2" color="text.secondary" gutterBottom>
          Fill invoice details and items. Live preview below updates instantly.
        </Typography>

        <Divider sx={{ mb: 2 }} />

        <PurchaseInvoiceForm
          form={form}
          warehouses={warehouses}
          updateField={updateField}
          updateItem={updateItem}
          addItemRow={addItemRow}
          removeItemRow={removeItemRow}
        />

        <Box className="purchase-preview-root">
          <Typography variant="h6" sx={{ mt: 2 }}>
            Purchase Invoice Preview
          </Typography>
          <PurchaseInvoicePreview data={form} className="printable-area" />

          <Box sx={{ mt: 2, display: "flex", gap: 2, flexWrap: "wrap" }}>
            <Button
              variant="contained"
              onClick={handleSubmitInvoice}
              disabled={isSaving}
            >
              {isSaving ? "Saving..." : "Save Purchase Invoice"}
            </Button>

            <Button variant="contained" onClick={handlePrint}>
              Print / Save as PDF
            </Button>

            <Button variant="outlined" color="error" onClick={handleClearForm}>
              Clear All
            </Button>
          </Box>
        </Box>
      </Paper>
    </Container>
  );
}

/* Number to words - Indian format (simple) */
function numberToWordsIndian(num) {
  if (!num && num !== 0) return "";
  if (num === 0) return "Zero Only";
  const a = [
    "",
    "One",
    "Two",
    "Three",
    "Four",
    "Five",
    "Six",
    "Seven",
    "Eight",
    "Nine",
    "Ten",
    "Eleven",
    "Twelve",
    "Thirteen",
    "Fourteen",
    "Fifteen",
    "Sixteen",
    "Seventeen",
    "Eighteen",
    "Nineteen",
  ];
  const b = [
    "",
    "",
    "Twenty",
    "Thirty",
    "Forty",
    "Fifty",
    "Sixty",
    "Seventy",
    "Eighty",
    "Ninety",
  ];
  const numStr = num.toString();
  if (numStr.length > 9) return "Overflow";
  const n = ("000000000" + num)
    .substr(-9)
    .match(/^(\d{2})(\d{2})(\d{2})(\d{3})$/);
  if (!n) return "";
  let str = "";
  str +=
    n[1] != 0
      ? (a[Number(n[1])] || b[n[1][0]] + " " + a[n[1][1]]) + " Crore "
      : "";
  str +=
    n[2] != 0
      ? (a[Number(n[2])] || b[n[2][0]] + " " + a[n[2][1]]) + " Lakh "
      : "";
  str +=
    n[3] != 0
      ? (a[Number(n[3])] || b[n[3][0]] + " " + a[n[3][1]]) + " Thousand "
      : "";
  str +=
    n[4] != 0 ? (a[Number(n[4])] || b[n[4][0]] + " " + a[n[4][1]]) + " " : "";
  return str.trim() + " Only";
}
